PlusOffSet/Controllers/CustomerController.cs
using Microsoft.AspNetCore.Mvc;
using PlusOffSet.DAL;
using PlusOffSet.Models;

namespace PlusOffSet.Controllers
{
    public class CustomerController : Controller
    {
        // private readonly CustomerDAL _dAL;
        CustomerDAL _customerDAL = new CustomerDAL();

       /* public CustomerController(CustomerDAL _customerDAL)
        {
            _customerDAL = CustomerDAL;
        }*/
        [HttpGet]
        public ActionResult Index()
        {
            try
            {
                var customers = _customerDAL.GetAllcustomer();

                if (customers.Count == 0)
                {
                    TempData["InfoMessage"] = "Currently customer not available in the Database.";
                }
                return View(customers);
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = ex.Message;
                return View();
            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Index(customer cm)
        {
            if (ModelState.IsValid)
            {

            }
            return View();
        }


        // GET: Customer/Create
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Customer/Create
        [HttpPost]
        public ActionResult Create(customer customer)
        {
            try
            {
                int id = 0;

                if (ModelState.IsValid)
                {
                    id = _customerDAL.Insertcustomer(customer);

                    if (id > 0)
                    {
                        TempData["SuccessMessage"] = "Customer details saved successfully.";
                    }
                    else
                    {
                        TempData["ErrorMessage"] = "Unable to insert the customer";
                    }
                }
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = ex.Message;
                return View();
            }
        }
        //POST: Customer/Edit/
        public ActionResult Edit(int Id)
        {
            try
            {
                var customerList = _customerDAL.GetcustomerID(Id).FirstOrDefault();

                if (customerList == null)
                {
                    TempData["ErrorMessage"] = "Customer details not available with the customer Id : " + Id;
                    return RedirectToAction("Index");
                }
                return View(customerList);
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = ex.Message;
                return View();
            }
        }

        // POST: Customer/Edit/
        [HttpPost, ActionName("Edit")]
        public ActionResult UpdateCustomer(customer customer)
        {
            try
            {
                int Id = 0;

                if (ModelState.IsValid)
                {
                    Id = _customerDAL.UpdateCustomer(customer);

                    if (Id > 0)
                    {
                        TempData["SuccessMessage"] = "Customer details updated successfully.";
                    }
                    else
                    {
                        TempData["ErrorMessage"] = "Unable to update the customer.";
                    }
                }
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = ex.Message;
                return View();
            }
        }
        public ActionResult Delete(int id)
        {
            try
            {
                var customerList = _customerDAL.GetcustomerID(id).FirstOrDefault();

                if (customerList == null)
                {
                    TempData["ErrorMessage"] = "Customer details not available with the customer Id : " + id;
                    return RedirectToAction("Index");
                }
                return View(customerList);
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = ex.Message;
                return View();
            }
        }

        // POST: Customer/Delete/5
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                int customerid = 0;

                if (ModelState.IsValid)
                {
                    customerid = _customerDAL.DeleteCustomer(id);

                    if (customerid > 0)
                    {
                        TempData["SuccessMessage"] = "Customer deleted successfully";
                    }
                    else
                    {
                        TempData["ErrorMessage"] = "Customer to delete the customer";
                    }
                }
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = ex.Message;
                return View();
            }
        }

    }
}

PlusOffSet/Controllers/HomesController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using PlusOffSet.Models;

namespace PlusOffSet.Controllers
{
    public class HomesController : Controller
    {
        private readonly ILogger<HomesController> _logger;

        public HomesController(ILogger<HomesController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PlusOffSet/Controllers/JobController.cs
using Microsoft.AspNetCore.Mvc;
using PlusOffSet.DAL;
using PlusOffSet.Models;
using System;
using System.Diagnostics;
using System.Linq;

namespace PlusOffSet.Controllers
{
    public class JobController : Controller
    {
        private readonly JobDAL _jobDAL;

        public JobController(JobDAL jobDAL)
        {
            _jobDAL = jobDAL;
        }

        [HttpGet]
        
        public ActionResult Index()
        {
            try
            {
                var jobList = _jobDAL.GetAlljob();

                if (jobList.Count == 0)
                {
                    TempData["InfoMessage"] = "Currently job not available in the Database.";

                }

                return View(jobList);
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = ex.Message;
                return View();
            }
        }
        public ActionResult Index(DateTime startDate, DateTime endDate)
        {
            JobDAL jobReportDAL = new JobDAL();
            List<job_master> jobReports = jobReportDAL.GetJobReportByCreatedDate(startDate, endDate);

            return View(jobReports);
        }
        [HttpGet]
        public ActionResult GenerateJobno()
        {
           
            job_master jobNo = _jobDAL.GenerateJobNo();

            return View(jobNo);
        }
        [HttpGet]
        public ActionResult job_create()
        {
            job_master jobNo = _jobDAL.GenerateJobNo();

            return View(jobNo);
        }

        [HttpPost]
        public ActionResult job_create(job_master job)
        {
            try
            {
                int Id = 0;
                job.created_date = DateTime.Today;
                if (ModelState.IsValid)
                {
                    Id = _jobDAL.Insertjob(job);

                    if (Id > 0)
                    {
                        TempData["SuccessMessage"] = "job details saved successfully.";
                    }
                    else
                    {
                        TempData["ErrorMessage"] = "Unable to insert the job.";
                    }
                }

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = ex.Message;
                return View();
            }
        }

        [HttpGet]
        public ActionResult job_Edit(int Id)
        {
            try
            {
                var jobList = _jobDAL.GetjobID(Id).FirstOrDefault();

                if (jobList == null)
                {
                    TempData["ErrorMessage"] = "job details not available with the job Id : " + Id;
                    return RedirectToAction("Index");
                }

                return View(jobList);
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = ex.Message;
                return View();
            }
        }
        [HttpGet]
        public ActionResult job_view(int Id)
        {
            try
            {
                var jobList = _jobDAL.GetjobID(Id).FirstOrDefault();

                if (jobList == null)
                {
                    TempData["ErrorMessage"] = "job details not available with the job Id : " + Id;
                    return RedirectToAction("Index");
                }

                return View(jobList);
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = ex.Message;
                return View();
            }
        }
        
        [HttpPost]
        public ActionResult job_Edit(job_master job)
        {
            try
            {
                int Id = 0;

                if (ModelState.IsValid)
                {
                    Id = _jobDAL.Updatejob(job);

                    if (Id > 0)
                    {
                        TempData["SuccessMessage"] = "job details updated successfully.";
                    }
                    else
                    {
                        TempData["ErrorMessage"] = "Unable to update the job.";
                    }
                }

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = ex.Message;
                return View();
            }
        }

        
        public ActionResult job_Delete(int Id)
        {
            try
            {
                var jobList = _jobDAL.GetjobID(Id).FirstOrDefault();

                if (jobList == null)
                {
                    TempData["ErrorMessage"] = "job details not available with the job Id : " + Id;
                    return RedirectToAction("Index");
                }

                return View(jobList);
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = ex.Message;
                return View();
            }
        }

        [HttpPost, ActionName("job_Delete")]
        public ActionResult DeleteConfirmed(int Id)
        {
            try
            {
                int jobId = 0;

                if (ModelState.IsValid)
                {
                    jobId = _jobDAL.Deletejob(Id);

                    if (jobId > 0)
                    {
                        TempData["SuccessMessage"] = "job deleted successfully.";
                    }
                    else
                    {
                        TempData["ErrorMessage"] = "Unable to delete the job.";
                    }
                }

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = ex.Message;
                return View();
            }
        }
    }
}

PlusOffSet/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]  PlusOffSet</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PlusOffSet.styles.css" asp-append-version="true" />
    <link rel="stylesheet"href="https://cdn.datatables.net/1.13.4/css/jquery.dataTables.min.css"/>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.datatables.net/1.11.4/js/jquery.dataTables.min.js"></script>
    <link rel="stylesheet" href="https://cdn.datatables.net/1.11.4/css/jquery.dataTables.min.css" />
    <script src="https://cdn.datatables.net/buttons/1.7.1/js/dataTables.buttons.min.js"></script>
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.7.1/css/buttons.dataTables.min.css" />
    <script src="https://cdn.datatables.net/buttons/1.7.1/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.7.1/js/buttons.print.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <!-- Include jQuery UI library -->
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <link href="https://kendo.cdn.telerik.com/2021.2.511/styles/kendo.common.min.css" rel="stylesheet" />
    <link href="https://kendo.cdn.telerik.com/2021.2.511/styles/kendo.default.min.css" rel="stylesheet" />
    <script src="https://kendo.cdn.telerik.com/2021.2.511/js/jquery.min.js"></script>
    <script src="https://kendo.cdn.telerik.com/2021.2.511/js/kendo.all.min.js"></script>
   
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm text-white bg-dark">
            <div class="container-fluid">
            <a class="navbar-brand text-white" asp-area="" asp-controller="Homes" asp-action="Index">PlusOffSet</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between" id="navbarNav">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-white" href="@Url.Action("Index", "Homes")">Home</a>
                    </li>
                    <li class="nav-item">
                            <a class="nav-link text-white" href="@Url.Action("Index", "Job")">Job</a>
                    </li>
                    <li class="nav-item">
                            <a class="nav-link text-white" href="@Url.Action("Index", "Customer")">Customer</a>
                    </li>
                      
                </ul>
            </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-black">
        <div class="container">
            &copy; 2023 - PlusOffSet - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

<!--<nav class="navbar navbar-expand-sm navbar-brand text-white bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index">PlusOffSet</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">
                    <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Job</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link text-white" asp-area="" asp-controller="customer">customer</a>
                </li>

            </ul>
        </div>
    </div>
</nav>-->